### ISSUE TITLE
执行python3 setup.py -c config-siflower-18.x.yml及后续内容报错

### ISSUE THREAD

**Issue by gilgamesh1124** [gl-inet/gl-infra-builder#1]
执行python3 setup.py -c config-siflower-18.x.yml后
提示：error: 路径规格 'develop' 未匹配任何 git 已知文件
如果忽略，在openwrt-18.06目录下继续执行./scripts/gen_config.py list
则提示-bash: ./scripts/gen_config.py: 没有那个文件或目录
没有办法获取设备清单

**Comment by dengxinfa** [comment]
在clone gl-infra-builder之后，有任何修改吗？
能否再重新试一遍？

我这边复测没有发现问题；
