### ISSUE TITLE
按照教程编译SFT1200固件报错

### ISSUE THREAD

**Issue by olochi** [gl-inet/gl-infra-builder#10]
挂T，执行命令
~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200

报错
WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
#
# configuration written to .config
#
Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!

**Comment by 588q9** [comment]
> 挂T，执行命令 ~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200
> 
> 报错 WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
> # configuration written to .config
> 
> Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!

我的也是sft1200，我用的kali来搞编译环境，但是没有target_siflower_gl-sft1200文件。想问一下你的编译环境是什么

**Comment by olochi** [comment]
> > 挂T，执行命令 ~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200
> > 报错 WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
> > # configuration written to .config
> > Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!
> 
> 我的也是sft1200，我用的kali来搞编译环境，但是没有target_siflower_gl-sft1200文件。想问一下你的编译环境是什么

就是缺文件，不知道怎么解决啊，和环境没关系，我是18.04。。。。估计是官方维护的太慢了。。对SFT1200

**Comment by 588q9** [comment]
唉，搞了三天都没搞定




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月18日(星期三) 晚上8:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gl-inet/gl-infra-builder] 按照教程编译SFT1200固件报错 (Issue #10)





   
挂T，执行命令 ~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200
 报错 WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
 
configuration written to .config
 
Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!
  
我的也是sft1200，我用的kali来搞编译环境，但是没有target_siflower_gl-sft1200文件。想问一下你的编译环境是什么
  
就是缺文件，不知道怎么解决啊，和环境没关系，我是18.04。。。。估计是官方维护的太慢了。。对SFT1200

**Comment by zhangguanzhang** [comment]
> > > 挂T，执行命令 ~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200
> > > 报错 WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
> > > # configuration written to .config
> > > Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!
> > 
> > 
> > 我的也是sft1200，我用的kali来搞编译环境，但是没有target_siflower_gl-sft1200文件。想问一下你的编译环境是什么
> 
> 就是缺文件，不知道怎么解决啊，和环境没关系，我是ubuntu18.04。。。。估计是官方维护的太慢了。。对SFT1200。。你不要用这个库，用imagebuilder，可以正常编译，但是是18.06。。。

你试试op官方的18.06分支试试，我是参照这个 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=5030255&extra=&authorid=305677&page=1
make之前需要有很多修改的地方，我摸索了好久

**Comment by dengxinfa** [comment]
> 挂T，执行命令 ~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200
> 
> 报错 WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
> 
> # configuration written to .config
> Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!

SFT1200是进入这个目录哦 gl-infra-builder/openwrt-18.06/siflower/openwrt-18.06

**Comment by zhangguanzhang** [comment]
@KelvinSoh8 老铁我基于op官方18.06编译，你需要哪些插件

**Comment by olochi** [comment]
> 



> > 挂T，执行命令 ~/gl-infra-builder/openwrt-19.07/openwrt-19.07.7$ ./scripts/gen_config.py target_siflower_gl-sft1200
> > 报错 WARNING: Makefile 'package/feeds/packages/ksmbd/Makefile' has a dependency on 'kmod-crypto-arc4', which does not exist
> > # configuration written to .config
> > Error: Cant not find the profile 'SF19A28-GL-SFT1200'! Please check again!
> 
> SFT1200是进入这个目录哦 gl-infra-builder/openwrt-18.06/siflower/openwrt-18.06

你应该是用imagebuilder编译的吧？gl-infra-builder/openwrt-18.06下面没有siflower/openwrt-18.06这个目录。。按照python3 setup.py -c config-18.x.yml官方教程执行完后

**Comment by 588q9** [comment]
蟹蟹哥们，但我不想折腾了，有这时间不如在尸体机上弄软路由或者用别人编译的固件



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gl-inet/gl-infra-builder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 晚上10:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gl-inet/gl-infra-builder] 按照教程编译SFT1200固件报错 (Issue #10)





 
@KelvinSoh8 老铁我基于op官方18.06编译，你需要哪些插件
