### ISSUE TITLE
unable to set 2.4GHZ in ax mode

### ISSUE THREAD

**Issue by prmfeddema** [gl-inet/gl-infra-builder#28]
When setting the 2.4 GHZ band to ax mode it will jump back to 11n (from 11ax). This is a confirmed bug

**Comment by luochongjun** [comment]
This is a BUG and will be fix

**Comment by luochongjun** [comment]
Fixed in 4.0.1_release2

**Comment by prmfeddema** [comment]
Issue closed - thank you guys for fixing this fast.
