### ISSUE TITLE
4.0.1 pre-release 3 does not install?

### ISSUE THREAD

**Issue by prmfeddema** [gl-inet/gl-infra-builder#29]
Results in error message (to be detailed later) when trying to install though admin page when using .tar file

**Comment by luochongjun** [comment]
If the from 5.4 kernel to 4.0.1_release2, a message is displayed indicating that the kernel version is upgraded.

**Comment by prmfeddema** [comment]
Problem was on my (user) side. After unzipping the .tar.gz file i needed to untar the resulting .tar file. then i found the firmware .tar file. This one upgraded fine.
