### ISSUE TITLE
[axt1800]  opkg_install_cmd: Cannot install package dockerd

### ISSUE THREAD

**Issue by Hesidv** [gl-inet/gl-infra-builder#30]
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency kmod-dm for libdevmapper-selinux
 * pkg_hash_check_unresolved: cannot find dependency kmod-dm for libdevmapper
 * pkg_hash_fetch_best_installation_candidate: Packages for libdevmapper found, but incompatible with the architectures configured
 * pkg_hash_check_unresolved: cannot find dependency kmod-ikconfig for dockerd
 * pkg_hash_check_unresolved: cannot find dependency kmod-nf-ipvs for dockerd
 * pkg_hash_check_unresolved: cannot find dependency kmod-veth for dockerd
 * pkg_hash_fetch_best_installation_candidate: Packages for dockerd found, but incompatible with the architectures configured

**Comment by luochongjun** [comment]
Will be fixed on version 4.0.1.
