### ISSUE TITLE
config file location

### ISSUE THREAD

**Issue by Tjkent88** [gl-inet/gl-infra-builder#31]
I had to change the script to match the directions for me personally. 

https://github.com/gl-inet/gl-infra-builder/blob/main/setup.py#L212

`config = "config-19.x.yml"`  <--- orginal

`config = "configs/config-19.x.yml"`  <--- change

**Comment by luochongjun** [comment]
We should specify a specific file path at the time of operation; restricting the configuration file path to the configs directory loses flexibility.
