### ISSUE TITLE
gl-ax1800 UI4.0怎么不更新了啊?

### ISSUE THREAD

**Issue by monw** [gl-inet/gl-infra-builder#38]
如题

**Comment by monw** [comment]
![Screenshot_2022-09-04-22-06-21-63_b5a5c5cb02ca09c784c5d88160e2ec24.jpg](https://user-images.githubusercontent.com/65690955/188333706-1f246672-5ae0-4cf3-97d2-4b4071282008.jpg)这glinet APP竟然占18g内存空间，只因为用里面的文件管理观看了路由器TF卡的视频，求解决。

**Comment by zheshifandian** [comment]
清下缓存不就得了

**Comment by luochongjun** [comment]
感觉文不对题啊，具体啥问题？

**Comment by monw** [comment]
用APP看sd卡视频，会产生大量缓存数据
