### ISSUE TITLE
提示缺失.yml文件

### ISSUE THREAD

**Issue by gilgamesh1124** [gl-inet/gl-infra-builder#41]
运行python3 setup.py等相关命令后，提示缺失config-xx.yml文件
麻烦把说明补全，谢谢。

**Comment by gilgamesh1124** [comment]
这个解决了，然后是要有访问https://gitlab.com/gl.sdk4.0/gl.router/gl-sdk4-collect.git;v4.1.0的权限，这是怎么搞？

**Comment by luochongjun** [comment]
这个是我们的私有包，不提供源代码
