### ISSUE TITLE
MT1300 4.1.0beta版本不支持tf卡

### ISSUE THREAD

**Issue by podipod** [gl-inet/gl-infra-builder#44]
MT1300 4.1.0beta版本不支持tf卡，希望更新上驱动

**Comment by dengxinfa** [comment]
已修复，请从链接获取固件升级测试
[](https://github.com/gl-inet/gl-infra-builder/releases/tag/v4.1.0_mt1300_beta2)

**Comment by dengxinfa** [comment]
https://github.com/gl-inet/gl-infra-builder/releases/tag/v4.1.0_mt1300_beta2
