### ISSUE TITLE
Bluetooth stays enabled, broadcasting ID, on AX1800-release5

### ISSUE THREAD

**Issue by ean365** [gl-inet/gl-infra-builder#48]
Bluetooth is remaining enabled and broadcasting its ID on the Flint AX1800 using release-5 firmware.
I understand that it should be automatically disabled if the router is already setup, but my router is setup and bluetooth is not disabled.
Please consider adding a switch to the web GUI to force turn it off.
Also, is there a shell command that can be used to turn it off when ssh'ed into the router?

Thanks!  It seems to be a great router, and I am pretty happy with it so far.

**Comment by handongming** [comment]
It's a bug on release2 if you do keep setting sysupgrade. Please do a factory reset for a workaround.  This keep setting sysupgrade issue will be addressed in 4.1.1 version, thank you.

**Comment by ean365** [comment]
I am using release5, not release2.  So it is also a bug in release5.
The `glconfig.general.blueconfig='1'` setting is what I needed.  It works for now.
Thank you.

**Comment by handongming** [comment]
Verified fixed in release 6 thank you.
