### ISSUE TITLE
AXT1800 build failed (5.4kernel)

### ISSUE THREAD

**Issue by mengbaixiaotang** [gl-inet/gl-infra-builder#53]
发现了个问题，在编译的时候backports-20210222_001-5.4.164-b157d2276.tar.bz2这个文件的hash和获取到的对不上，导致缺少文件编译失败，看起来应该像是上游的问题，目前尝试手动修改此文件的哈希值为当前值，正在尝试编译
错误代码如下
文件hash不匹配：Hash of the downloaded file does not match (file: e92901b5150c6d9ac7eafc83187d8819f2c5620c2298504d84f7ecba6423bc71, requested: 6dfc49a96e0ba9b23d8bae0675105ea4b4c337c4869ee1fd31f65220ab0dc131) - deleting download.
编译停止错误：make[3]: *** [Makefile:269: /home/runner/gl-infra-builder/wlan-ap/openwrt/dl/backports-20210222_001-5.4.164-b157d2276.tar.bz2] Error 2

Translate by Google: I found a problem that affects the compilation process, a file named ’backports-20210222_001-5.4.164-b157d2276.tar.bz2’ can not correspond to its hash value, causing compilation errors. I`m trying changing the hash by hand to make it successfully compiled
The error code is as follows
File hash does not match: Hash of the downloaded file does not match (file: e92901b5150c6d9ac7eafc83187d8819f2c5620c2298504d84f7ecba6423bc71, requested: 6dfc49a96e0ba9b23d8bae0675105ea4b4c337c4869ee1fd31f65220ab0dc131) - deleting download.
Compile stop error: make[3]: *** [Makefile:269: /home/runner/gl-infra-builder/wlan-ap/openwrt/dl/backports-20210222_001-5.4.164-b157d2276.tar.bz2] Error 2

**Comment by Jinnrry** [comment]
同样问题

**Comment by Jinnrry** [comment]
你是怎么改的？改完编译能过吗

**Comment by smilekevin** [comment]
https://github.com/smilekevin/OpenWrt-GL-AX1800/blob/smilekevin-personalized/patch_axt1800_5-4/0004-feeds-wifi-ax-mac80211-makefile.patch
把这个文件丢到/workdir/gl-infra-builder/patches-wlan-ap-5.4 下

**Comment by mengbaixiaotang** [comment]
> 你是怎么改的？改完编译能过吗

改完以后可以编译完，但是5.4内核问题太多，还是先用4.4的顶着吧

**Comment by mengbaixiaotang** [comment]
> https://github.com/smilekevin/OpenWrt-GL-AX1800/blob/smilekevin-personalized/patch_axt1800_5-4/0004-feeds-wifi-ax-mac80211-makefile.patch 把这个文件丢到/workdir/gl-infra-builder/patches-wlan-ap-5.4 下

谢谢大佬的法子，现在我就在试着更新4.4的musl了，刚处理完musl的patch后gcc的就寄了，还不知道什么原因
