### ISSUE TITLE
HWNAT is not working for iptables REDIRECT

### ISSUE THREAD

**Issue by 0neday** [gl-inet/gl-infra-builder#69]
I use `ipset` and iptables transport proxy (using tcp REDIRECT)
```
iptables -t nat -I PREROUTING -p tcp -m set --match-set gfw dst -m multiport --dports 80,443,1883 -j REDIRECT --to-ports 1234
```

found that HNAT is not working, except for throughout that is not ` gfw of ipset` 
```
root@MT-3000:~#  cat /sys/kernel/debug/hnat/hnat_entry
============================
PPE_ID = 0
NAPT(1444): 192.168.1.32:49613->192.168.1.2:21063 => 192.168.1.32:49613->192.168.1.2:21063
NAPT(6156): 192.168.1.99:64280->192.168.1.2:8123 => 192.168.1.99:64280->192.168.1.2:8123
NAPT(6157): 192.168.1.2:8123->192.168.1.99:64280 => 192.168.1.2:8123->192.168.1.99:64280
NAPT(6192): 192.168.1.99:64279->192.168.1.2:8123 => 192.168.1.99:64279->192.168.1.2:8123
NAPT(7216): 192.168.1.2:8123->192.168.1.99:64279 => 192.168.1.2:8123->192.168.1.99:64279
Total State = BIND cnt = 5

```

**Comment by padavanonly** [comment]
Redirect packets will bypass hnat module and be forwarded by cpu.

**Comment by 0neday** [comment]
> bypass hnat module and be forwarded by cpu

 I have test using `tproxy(pure transport)` and using DNAT
```
iptables -t nat -I PREROUTING -p tcp -m set --match-set gfw dst -m multiport --dports 80,443,1883  -j DNAT --to-destination 192.168.1.1:1234
```
however, have no lucky.

Do any method to fix it?

**Comment by padavanonly** [comment]
LAN<->PPE<->WIFI   WAN<->PPE<->WIFI   WAN<->PPE<->LAN


PPE can't offload  packets that the source or destination  is router itself.

**Comment by 0neday** [comment]
> PPE can't offload packets that the source or destination is router itself

thank you, that mean we can not apply HWNAT to router when it  have a global proxy

**Comment by padavanonly** [comment]
> > PPE can't offload packets that the source or destination is router itself
> 
> thank you, that mean we can not apply HWNAT to router when it have a global proxy

Assuming that PPE supports this situation, CPU still needs to do NAT work for the arriving packet that comes from PPE. So it's meaningless for proxy with HNAT working.
