### ISSUE TITLE
编译 wlan-ap toplevel.mk:230 错误

### ISSUE THREAD

**Issue by nbpanda1978** [gl-inet/gl-infra-builder#7]
错误提示：
mv -f $depbase.Tpo $depbase.Po
make[3]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/lzma'
time: tools/lzma/compile#0.05#0.01#0.12
make[3]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/mtools'
time: tools/mtools/compile#0.04#0.02#0.10
make[3]: Entering directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/sstrip'
make[3]: Entering directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/patch-image'
In file included from /usr/include/signal.h:328,
                 from ./signal.h:52,
                 from c-stack.c:49:
c-stack.c:55:26: error: missing binary operator before token "("
   55 | #elif HAVE_LIBSIGSEGV && SIGSTKSZ < 16384
      |                          ^~~~~~~~
make[7]: *** [Makefile:1910: c-stack.o] Error 1
make[7]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/build_dir/host/m4-1.4.18/lib'
make[6]: *** [Makefile:1674: all] Error 2
make[6]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/build_dir/host/m4-1.4.18/lib'
make[5]: *** [Makefile:1572: all-recursive] Error 1
make[5]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/build_dir/host/m4-1.4.18'
make[4]: *** [Makefile:1528: all] Error 2
make[4]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/build_dir/host/m4-1.4.18'
make[3]: *** [Makefile:30: /home/szm/software/gl-infra-builder/wlan-ap/openwrt/build_dir/host/m4-1.4.18/.built] Error 2
make[3]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/m4'
time: tools/m4/compile#0.13#0.07#0.29
    ERROR: tools/m4 failed to build.
make[2]: *** [tools/Makefile:161: tools/m4/compile] Error 1
make[2]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/patch-image'
time: tools/patch-image/compile#0.04#0.00#0.07
make[3]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt/tools/sstrip'
time: tools/sstrip/compile#0.03#0.02#0.09
make[2]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt'
make[1]: *** [tools/Makefile:157: /home/szm/software/gl-infra-builder/wlan-ap/openwrt/staging_dir/host/stamp/.tools_compile_yyynyynnyyynyyyyyynyynnyyynynyyyyyyyyyyyyyyyynynnyyyyyyy] Error 2
make[1]: Leaving directory '/home/szm/software/gl-infra-builder/wlan-ap/openwrt'
make: *** [/home/szm/software/gl-infra-builder/wlan-ap/openwrt/include/toplevel.mk:230：world] 错误 2

ubunti 21.10

**Comment by nbpanda1978** [comment]
在ubuntu20下编译无问题。

**Comment by luochongjun** [comment]
看下这个链接呢
https://lists.gnu.org/archive/html/bug-m4/2021-03/msg00000.html
